version: "3.1"
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - nodeapp-network

  node:
    container_name: nodeapp
    image: nodeapp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/var/www"
    ports:
      - "3000:3000"
    networks:
      - nodeapp-network
    depends_on:
      - mongo
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge
  dario-network:
    driver: bridge
